### ISSUE TITLE
(ShowHiddenChannels) Cannot access channels once permission is given

### ISSUE THREAD

**Issue by starspritechippy** [X1nto/AliucordPlugins#2]
For the ShowHiddenChannels plugin, channels don't update to be accessible when you're given permission.

To reproduce: 
- Be in a server with an inaccessible channel
- Receive a role to get access to that channel
- Try to enter the channel

There could be a "force access" option in a locked channel's context menu that would result in a network error when the channel really isn't accessible, but this is also somewhat misleading.

**Comment by X1nto** [comment]
Thanks for reporting, I'll definitely take a look.

**Comment by starspritechippy** [comment]
Yep, tested it just now and can confirm the bug no longer occurs. Thank you!
