### ISSUE TITLE
(Nitro Spoof) Crashes my aliucord (v101.3). And grey out emojis in reaction emoji tab.

### ISSUE THREAD

**Issue by WitherredAway** [X1nto/AliucordPlugins#28]
- Trying to open the settings of this plugin crashes my aliucord (v101.3). Here's the [crash log](https://pastebin.com/DefD6jCU). 
- Please make it so it greys out emojis in the reaction emojis tab. Since i can't react with inaccessible emojis, it makes it very hard to find emojis that i can actually use since they're *all* ungreyed.

**Comment by X1nto** [comment]
should be fixed now

**Comment by WitherredAway** [comment]
The crash bug is fixed, but will the un-grey thing be fixed for reactions?

**Comment by X1nto** [comment]
> The crash bug is fixed, but will the un-grey thing be fixed for reactions?

For reactions I doubt it's possible to fix yet, but I'll take a look
