### ISSUE TITLE
Canceled Nitro Sub Breaks Nitro Spoof 

### ISSUE THREAD

**Issue by RealFakeGitter** [X1nto/AliucordPlugins#50]
Hi, I previously tried to get help with this via this via the Aliucord Server, however no one seems to have come across this strange bug. The account i am on used to have nitro, it was a playstore sub if that matters, however that has since long been canceled. 
I have the NitroSpoof plugin on and Enabled, and additionally it ****_WORKS_**** In other accounts, but in this specific account, the only one that used to have nitro, instead of it converting the Emojis to Gifs it just writes the Emoji as Like for example if it was PepeHands it will write :pepehands: and then it either gives an error or it just sends the text with no emoji. I am attaching a screen recording. 
Just FYI troubleshooting i tried. 
I have tried to uninstall ALL other plugins and themes and have ONLY nitro spoof.
I have tried to Re-Install Aliucord all together with only nitro spoof. 
I actually even factory reset my entire phone (for another reason) but then reinstalled Aliucord, with only nitro spoof.
Also mentioned I've tried it on accounts that never had nitro and it works so it seems that ever having nitro (even when EXPIRED ) somehow is breaking this plugin

https://user-images.githubusercontent.com/105574409/225733689-761fe588-6aa5-45de-9843-6b23670eeec5.mp4

Thank you for any help!!!

**Comment by X1nto** [comment]
Just pushed out 1.0.10 with some changes by @Delphox in #55. The PR was related to the server boosts, but see if that fixes the issue.

**Comment by RealFakeGitter** [comment]
> Just pushed out 1.0.10 with some changes by @Delphox in #55. The PR was related to the server boosts, but see if that fixes the issue.

Well, the thing is I reported this over a year ago, since then the problem seems to have resolved itself, Can't really say what exactly fixed it, but at the moment nitro-spoof works fine

**Comment by RealFakeGitter** [comment]
> Just pushed out 1.0.10 with some changes by @Delphox in #55. The PR was related to the server boosts, but see if that fixes the issue.

Well, the thing is I reported this over a year ago, since then the problem seems to have resolved itself, Can't really say what exactly fixed it, but at the moment nitro-spoof works fine
