### ISSUE TITLE
Request for the HideBloat plugin

### ISSUE THREAD

**Issue by Me-dot-exe** [X1nto/AliucordPlugins#8]
remove the call and videocall buttons!

why is the mobile interface so annoying
![IMG_20210723_175959](https://user-images.githubusercontent.com/72972952/126772888-c6a096a1-0a2f-4302-abbb-876def989d99.jpg)

**Comment by Me-dot-exe** [comment]
I'm dumb, didn't know the request thing on GitHub exist

**Comment by Me-dot-exe** [comment]
idk if the "Issues" tab is the right place to request so i closed it .-.

**Comment by X1nto** [comment]
It's the right place don't worry

**Comment by X1nto** [comment]
Added in 1.1.0
![Screenshot_2021-07-23-19-50-51-853_com.aliucord.jpg](https://user-images.githubusercontent.com/48173186/126808364-195d6779-e277-4432-b9d7-61e4ed11be14.jpg)

**Comment by WheneverDev** [comment]
Looks like it broke 
![Screenshot_20210807-235831](https://user-images.githubusercontent.com/32911991/128614859-693b1f0f-411e-4899-b701-bcb18bec58ea.png)
