### ISSUE TITLE
Remove "(hidden)" text

### ISSUE THREAD

**Issue by bordoga-bordoga** [X1nto/AliucordPlugins#9]
It would be nice if the "(hidden)" text beside each hidden channel was removed. The crossed hashtag text-channel symbol is enough to indicate that a channel is a hidden channel. It would make it look nicer and cleaner imo.

**Comment by vy-storm** [comment]
Agreed!  An option would be good!  It is very bloaty like this imo

**Comment by X1nto** [comment]
removed in the new update
